
JNI_PATH := $(call my-dir)
LOCAL_PATH := $(JNI_PATH)

NATIVE_DIR := ../src/native

SOURCE_DIR := $(NATIVE_DIR)/common
PLATFORM_SRC_INCLUDE := $(LOCAL_PATH)/$(NATIVE_DIR)/unix/src
COMMON_SRC_INCLUDE := $(LOCAL_PATH)/$(SOURCE_DIR)

include $(CLEAR_VARS)

LOCAL_MODULE    := libpkcs11wrapper
LOCAL_CFLAGS	:= -I$(PLATFORM_SRC_INCLUDE) -I$(COMMON_SRC_INCLUDE) -DUNIX -DDEBUG
LOCAL_SRC_FILES := $(SOURCE_DIR)/pkcs11wrapper.c

#LOCAL_LDLIBS	:=
#LOCAL_PRELINK_MODULE := false

include $(BUILD_SHARED_LIBRARY)
